import re

md_path = r"C:\Users\thana\My Drive\GPO\Appendix 2_Module\Appendix 2_Enclosure 1.md"

with open(md_path, "r", encoding="utf-8") as f:
    content = f.read()

# Regex to remove base64 images generated by mammoth
# Mammoth generates images like ![alt text](data:image/...)
clean_content = re.sub(r'!\[.*?\]\(data:image/[^)]+\)', '[รูปภาพประกอบ (ลบออกแล้ว)]', content)

with open(md_path, "w", encoding="utf-8") as f:
    f.write(clean_content)

print(f"Cleaned images from {md_path}")
