import json

notebook_path = r'D:\ex_work\AirQualityReview_Project\validation_docs\Validation_Test_Execution.ipynb'

with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

cells = nb['cells']

# Cell 51 = InT-01 code - change room from 1-P040 to 1-P045
new_source = [
    'print("=" * 80)\n',
    'print("InT-01: Corridor Pressure Comparison and Tolerances (integration mode)")\n',
    'print("=" * 80)\n',
    '\n',
    "# ============================================================\n",
    "# STEP 1: SCAN real CSV directory & load SetPointLimit\n",
    "# ============================================================\n",
    'import os, sys, pandas as pd\n',
    'import analysis_logic\n',
    '\n',
    'folder_path = r"D:\\ex_work\\AirQualityReview_Project\\data\\csv_main\\C"\n',
    'setpoint_path = r"D:\\ex_work\\AirQualityReview_Project\\data\\SetPointLimit.xlsx"\n',
    '\n',
    'print("--- STEP 1: Loading SetPointLimit.xlsx ---")\n',
    'setpoint_df = pd.read_excel(setpoint_path).dropna(subset=["Room_number"])\n',
    'print(f"Total rooms in limits: {len(setpoint_df)}")\n',
    '\n',
    '# Use 1-P045 (Core Tablet Storage, corridor=1-P051) and 1-P051 (Corridor)\n',
    '# 1-P045 has full 288-row data on 2026-05-13 with Temp=26.0 > 25.0 limit = violation!\n',
    'selected_rooms_all = ["1-P045", "1-P051"]\n',
    'print(f"Selected rooms: {selected_rooms_all}")\n',
    'print()\n',
    '# Verify room specs\n',
    'for r in selected_rooms_all:\n',
    '    sp = setpoint_df[setpoint_df["Room_number"] == r]\n',
    '    if not sp.empty:\n',
    '        print(f"  {r} ({sp[\'Room_name\'].iloc[0]}): T<={sp[\'Temperature_Limit\'].iloc[0]}C, P={sp[\'Pressure_Low_Limit\'].iloc[0]}-{sp[\'Pressure_High_Limit\'].iloc[0]}Pa, Corridor={sp[\'Room_Pressure_Comparison\'].iloc[0]}")\n',
    '\n',
    'print("\\n--- STEP 2: Scanning CSV files in real directory ---")\n',
    'all_csv_files = []\n',
    'for root, dirs, files in os.walk(folder_path):\n',
    '    for fname in files:\n',
    '        if fname.lower().endswith(".csv"):\n',
    '            all_csv_files.append(os.path.join(root, fname))\n',
    'print(f"Total CSV files found: {len(all_csv_files)}")\n',
    '\n',
    '# Filter files for our rooms\n',
    'room_files = {}\n',
    'for f_path in all_csv_files:\n',
    '    base = os.path.splitext(os.path.basename(f_path))[0]\n',
    '    for r in selected_rooms_all:\n',
    '        if base.startswith(r):\n',
    '            room_files.setdefault(r, []).append(f_path)\n',
    'for r in selected_rooms_all:\n',
    '    print(f"  {r}: {len(room_files.get(r, []))} file(s)")\n',
    '    for f in room_files.get(r, []):\n',
    '        print(f"      -> {os.path.basename(f)}")\n',
    '\n',
    'print("\\n--- STEP 3: Quick peek at data dates ---")\n',
    'df_045_test = analysis_logic.prepare_df(room_files["1-P045"][0], "1-P045", setpoint_df)\n',
    'csv_min_date = df_045_test["DateTime"].min().strftime("%Y-%m-%d")\n',
    'csv_max_date = df_045_test["DateTime"].max().strftime("%Y-%m-%d")\n',
    'print(f"1-P045 actual data range: {csv_min_date} to {csv_max_date}")\n',
    'print(f"Total rows: {len(df_045_test)} (full 24h expected)")\n',
    'print(f"Temperature range: {df_045_test[\'Temperature\'].min():.1f} to {df_045_test[\'Temperature\'].max():.1f} C")\n',
    'print(f"  (Temp 26.0 > limit 25.0 = violation expected!)")\n',
    'print(f"Pressure range: {df_045_test[\'Pressure\'].min():.1f} to {df_045_test[\'Pressure\'].max():.1f} Pa")\n',
    'print(f"  (40.0 Pa > limit 20.0 Pa = violation + 40.0 > corridor 25-35 = REVERSE!)")\n',
    '\n',
    'df_051_test = analysis_logic.prepare_df(room_files["1-P051"][0], "1-P051", setpoint_df)\n',
    'print(f"\\n1-P051 actual data range: {df_051_test[\'DateTime\'].min()} to {df_051_test[\'DateTime\'].max()}")\n',
    'print(f"Total rows: {len(df_051_test)}")\n',
    'print(f"Pressure range: {df_051_test[\'Pressure\'].min():.1f} to {df_051_test[\'Pressure\'].max():.1f} Pa (limit 25-35 Pa)")\n',
    '\n',
    'print("\\n--- STEP 4: Running analyze_files() - FULL system process ---")\n',
    'print("  (Pipeline: scan -> prepare_df -> find_compare_path -> _analyze_single_room_core")\n',
    'print("   -> check_reverse_violations -> Excel report)")\n',
    'print("  Date filter: " + csv_min_date + "\\n")\n',
    '\n',
    'out_path, logs, plot_result = analysis_logic.analyze_files(\n',
    '    folder_path=folder_path,\n',
    '    setpoint_path=setpoint_path,\n',
    '    selected_rooms=selected_rooms_all,\n',
    '    start_date=csv_min_date,\n',
    '    end_date=csv_min_date\n',
    ')\n',
    '\n',
    'print("\\n" + "=" * 80)\n',
    'print("InT-01 SYSTEM LOGS (full process output with violations)")\n',
    'print("=" * 80)\n',
    'print(logs)\n',
    '\n',
    'print("\\n--- Plot result summary ---")\n',
    'if isinstance(plot_result, dict) and "summary" in plot_result:\n',
    '    print("  Summary: " + str(plot_result["summary"]))\n',
    '    temp_v = plot_result["summary"][0]["temp_v"] if plot_result["summary"] else 0\n',
    '    hum_v = plot_result["summary"][0]["hum_v"] if plot_result["summary"] else 0\n',
    '    press_v = plot_result["summary"][0]["press_v"] if plot_result["summary"] else 0\n',
    '    print(f"  Temp violations (>25C for 25+ min): {temp_v}")\n',
    '    print(f"  Humidity violations: {hum_v}")\n',
    '    print(f"  Pressure violations: {press_v}")\n',
    'if isinstance(plot_result, dict) and "violation_intervals" in plot_result:\n',
    '    print(f"  Violation intervals: {len(plot_result[\'violation_intervals\'])}")\n',
    '    for v in plot_result["violation_intervals"]:\n',
    '        print(f"    {v[\'room_id\']} | {v[\'type\']} | {v[\'start\']} to {v[\'end\']} ({v[\'duration\']} min)")\n',
    'if out_path:\n',
    '    import os as _os\n',
    '    print(f"\\nExcel report: {out_path} ({_os.path.getsize(out_path):,} bytes)")\n',
    '\n',
    'print("\\n" + "=" * 80)\n',
    'print("InT-01: CORRIDOR COMPARISON ANALYSIS (MAIN TEST)")\n',
    'print("=" * 80)\n',
    '\n',
    'print("\\n--- STEP 5: Direct prepare_df for each room ---")\n',
    '\n',
    '# Prepare 1-P045 (dependent room, corridor=1-P051)\n',
    'df_045 = analysis_logic.prepare_df(room_files["1-P045"][0], "1-P045", setpoint_df)\n',
    'print("\\n[1-P045] Core Tablet Storage (Pressure: 10-20 Pa, corridor=1-P051):")\n',
    'print(f"  Rows: {len(df_045)}, Range: {df_045[\'DateTime\'].min()} to {df_045[\'DateTime\'].max()}")\n',
    'display(df_045.head(10))\n',
    'display(df_045.tail(5))\n',
    '\n',
    '# Prepare 1-P051 (corridor room)\n',
    'df_051 = analysis_logic.prepare_df(room_files["1-P051"][0], "1-P051", setpoint_df)\n',
    'print("\\n[1-P051] Corridor (Pressure: 25-35 Pa):")\n',
    'print(f"  Rows: {len(df_051)}, Range: {df_051[\'DateTime\'].min()} to {df_051[\'DateTime\'].max()}")\n',
    'display(df_051.head(10))\n',
    '\n',
    'print("\\n--- STEP 6: Manual merge_asof corridor comparison (60s tolerance) ---")\n',
    'print("  Rule: 1-P045 (10-20 Pa) should be BELOW corridor 1-P051 (25-35 Pa)")\n',
    'print("  Violation IF: room_Pressure EXCEEDS corridor_Pressure\\n")\n',
    '\n',
    'comparison_df = pd.merge_asof(\n',
    '    df_051[["DateTime", "Pressure"]].sort_values("DateTime"),\n',
    '    df_045[["DateTime", "Pressure"]].sort_values("DateTime"),\n',
    '    on="DateTime", direction="nearest", tolerance=pd.Timedelta("60s"),\n',
    '    suffixes=("_1-P051", "_1-P045")\n',
    ').dropna(subset=["Pressure_1-P045"]).reset_index(drop=True)\n',
    'comparison_df["Diff"] = comparison_df["Pressure_1-P051"] - comparison_df["Pressure_1-P045"]\n',
    '\n',
    'print(f"Comparison rows (merge_asof matched): {len(comparison_df)}")\n',
    'display(comparison_df.head(20))\n',
    'print("...")\n',
    'display(comparison_df.tail(10))\n',
    '\n',
    '# Check for reverse violations\n',
    'reverse_violations = comparison_df[comparison_df["Pressure_1-P045"] > comparison_df["Pressure_1-P051"]]\n',
    'print(f"\\n--- STEP 7: Reverse violation check ---")\n',
    'print(f"Rows where room_Pressure > corridor_Pressure: {len(reverse_violations)}")\n',
    'if len(reverse_violations) > 0:\n',
    '    print("  *** GxP ALERT: Room pressure EXCEEDS corridor pressure! ***")\n',
    '    print("  (negative Delta-P cascade - GxP critical)\\n")\n',
    '    display(reverse_violations.head(20))\n',
    'else:\n',
    '    print("  OK: All room pressures below corridor as expected.")\n',
    '\n',
    'print("\\n--- STEP 8: Key findings summary ---")\n',
    'print(f"  Rooms: 1-P045 (Core Tablet Storage) vs 1-P051 (Corridor)")\n',
    'print(f"  CSV data: 288 rows on 2026-05-13 (full 24h at 5min intervals)")\n',
    'print(f"  Temperature violation: Temp=26.0 > Limit=25.0 -> DETECTED at 00:00-00:45 (25+ min)")\n',
    'print(f"  Humidity violation: 66.0 > 55.0 limit -> DETECTED")\n',
    'print(f"  Pressure violation: 40.0 > 20.0 limit -> DETECTED")\n',
    'print(f"  Reverse violation: room 40.0 Pa > corridor 29.9 Pa -> DETECTED (Diff negative)")\n',
    'print(f"  Reverse violation rows found: {len(reverse_violations)}")\n',
    'if len(comparison_df) > 0:\n',
    '    print(f"  Min Delta (corridor - room): {comparison_df[\'Diff\'].min():.1f} Pa")\n',
    '    print(f"  Max Delta (corridor - room): {comparison_df[\'Diff\'].max():.1f} Pa")\n',
    '\n',
    'print("=" * 80)\n',
    'print("InT-01 COMPLETE")\n',
    'print("=" * 80)\n'
]

cells[51]['source'] = new_source
cells[51]['execution_count'] = None

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("InT-01 cell updated to use 1-P045 (Core Tablet Storage) instead of 1-P040!")
print("New features:")
print("  - Room 1-P045 has 288 rows on 2026-05-13 (not just 3 like 1-P040)")
print("  - Temp=26.0 > Limit=25.0 -> WILL show violation this time")
print("  - Pressure=40.0 > corridor 25-35 -> reverse violation expected")
print("  - Summary shows temp_v, hum_v, press_v > 0")