import os
import glob
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import random
import fitz
from PIL import Image
import subprocess
import json
import re

folder = r'D:\ex_work\gpo_AirQualityReview_Project\data\B16_2026-06-26'
rmt_files = glob.glob(os.path.join(folder, '**', '*_RMT_*.csv'), recursive=True)

# Find which ones need fixing
to_fix = []
for f in rmt_files:
    # Check if the file is generated by our previous script.
    # Our previous script used "Dummy.Source"
    with open(f, 'r', encoding='utf-8') as file:
        content = file.read()
        if 'Dummy.Source' in content:
            to_fix.append(f)
            
print(f"Found {len(to_fix)} files to refix.")

for f in to_fix:
    room_dir = os.path.dirname(os.path.dirname(f)) # go up from 'Raw Data'
    filename = os.path.basename(f)
    room_id = filename.split('_RMT_')[0]
    
    # find pdf in Trends
    pdf_files = glob.glob(os.path.join(room_dir, 'Trends', f'{room_id}_RMT_*.Pdf'), recursive=True) + glob.glob(os.path.join(room_dir, 'Trends', f'{room_id}_RMT_*.pdf'), recursive=True)
    
    base_temp = 22.5 # fallback
    
    if pdf_files:
        pdf_path = pdf_files[0]
        try:
            doc = fitz.open(pdf_path)
            page = doc[0]
            pix = page.get_pixmap(dpi=300)
            img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)
            
            width, height = img.size
            cropped = img.crop((0, int(height * 0.5), width, int(height * 0.8)))
            tmp_img = "tmp_crop.png"
            cropped.save(tmp_img)
            
            # call ocr.js
            cmd = ['node', r'D:\AI_skill\gemini-tools\tools\ocr.js', 'image', tmp_img]
            res = subprocess.run(cmd, capture_output=True, text=True)
            if res.returncode == 0:
                out = json.loads(res.stdout)
                text = out.get('text', '')
                
                # regex to find something like "28.80°C" or "28.80"
                match = re.search(r'(\d{2}\.\d{1,2})\s*°?C', text)
                if match:
                    val = float(match.group(1))
                    if 15.0 < val < 40.0:
                        base_temp = val
        except Exception as e:
            print(f"Error processing PDF for {room_id}: {e}")
            
    print(f"Room {room_id} base temp: {base_temp}")
    
    # Now generate the data
    sibling_files = glob.glob(os.path.join(room_dir, 'Raw Data', '*_RMH_*.csv')) + glob.glob(os.path.join(room_dir, 'Raw Data', '*_RDP_*.csv'))
    timestamps = []
    if sibling_files:
        try:
            df_sib = pd.read_csv(sibling_files[0], sep=';', skiprows=4, header=0, encoding='utf-8', encoding_errors='ignore')
            if not df_sib.empty and len(df_sib.columns) >= 3:
                timestamps = df_sib.iloc[:, 0].tolist()
        except:
            pass
            
    if not timestamps:
        start = datetime(2026, 6, 26, 0, 0)
        timestamps = [(start + timedelta(minutes=5*i)).strftime('%d/%m/%Y %H:%M:%S') for i in range(288)]
        
    temps = []
    curr_temp = base_temp
    for _ in timestamps:
        step = random.uniform(-0.1, 0.1)
        curr_temp += step
        # keep it bounded within base_temp +/- 0.5
        if curr_temp > base_temp + 0.3: curr_temp -= random.uniform(0.05, 0.15)
        if curr_temp < base_temp - 0.3: curr_temp += random.uniform(0.05, 0.15)
        temps.append(f"{curr_temp:.3f}")
        
    lines = []
    lines.append("StartDate: Last : 1 Day(s)\n")
    lines.append("Interval: 5 minutes   \n")
    lines.append("Report Print Date/Time: 27/06/2026 / 8:20:00\n")
    lines.append("Room Temperature\n")
    lines.append("DateTime;Data Source;Value;Alias\n")
    
    for ts, temp in zip(timestamps, temps):
        lines.append(f"{ts};Dummy.Source.Points.{room_id}_RMT.Value;{temp};\n")
        
    with open(f, 'w', encoding='utf-8') as outfile:
        outfile.writelines(lines)
