import json

notebook_path = 'validation_docs/Validation_Test_Execution.ipynb'

with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Locate the cell index for InT-04
target_idx = None
for i, cell in enumerate(nb['cells']):
    if cell['cell_type'] == 'markdown' and '### InT-04:' in ''.join(cell['source']):
        target_idx = i
        break

if target_idx is None:
    raise ValueError("Could not find InT-04 cell in notebook!")

print(f"Target index is: {target_idx}")

new_cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### InT-04: Single Room Core Analysis & Corridor Validation (`_analyze_single_room_core`)\n",
            "This section verifies the core single room analysis engine, including violation time rules, data loss handling, and corridor reference comparisons."
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "#### InT-04-1: Parameter Violation 25-Minute Continuous Rule Verification\n",
            "Verifies that parameter violations are only logged if they persist for at least 25 minutes (6 continuous rows in 5-minute interval data)."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"-\" * 80)\n",
            "print(\"InT-04-1: Parameter Violation 25-Minute Continuous Rule Verification\")\n",
            "print(\"-\" * 80)\n",
            "\n",
            "import sys\n",
            "import os\n",
            "import pandas as pd\n",
            "from datetime import datetime, timedelta\n",
            "\n",
            "# Ensure project root is in system path\n",
            "project_dir = r'D:\\ex_work\\AirQualityReview_Project'\n",
            "if project_dir not in sys.path:\n",
            "    sys.path.append(project_dir)\n",
            "\n",
            "import analysis_logic\n",
            "\n",
            "# 1. Transient spike: 15 minutes of temperature violation (26 °C) from 10:00 to 10:15, then normal (22 °C)\n",
            "times_transient = [datetime(2026, 5, 30, 10, 0) + timedelta(minutes=5 * i) for i in range(12)]\n",
            "df_transient = pd.DataFrame({\n",
            "    'DateTime': times_transient,\n",
            "    'Temperature': [26.0, 26.0, 26.0, 26.0, 22.0, 22.0, 22.0, 22.0, 22.0, 22.0, 22.0, 22.0],\n",
            "    'Humidity': [50.0] * 12,\n",
            "    'Pressure': [15.0] * 12\n",
            "})\n",
            "\n",
            "# 2. Continuous violation: 25 minutes of temperature violation (26 °C) from 10:00 to 10:25, then normal (22 °C)\n",
            "df_continuous = pd.DataFrame({\n",
            "    'DateTime': times_transient,\n",
            "    'Temperature': [26.0, 26.0, 26.0, 26.0, 26.0, 26.0, 22.0, 22.0, 22.0, 22.0, 22.0, 22.0],\n",
            "    'Humidity': [50.0] * 12,\n",
            "    'Pressure': [15.0] * 12\n",
            "})\n",
            "\n",
            "setpoint_row = pd.DataFrame({\n",
            "    'Room_number': ['1-P040'],\n",
            "    'Room_name': ['Test Room'],\n",
            "    'Temperature_Limit': [25.0],\n",
            "    'Humidity_Low_Limit': [30.0],\n",
            "    'Humidity_High_Limit': [60.0],\n",
            "    'Pressure_Low_Limit': [10.0],\n",
            "    'Pressure_High_Limit': [20.0],\n",
            "    'Room_Pressure_Comparison': [None]\n",
            "})\n",
            "\n",
            "print(\"Step 1: Running transient spike data (15 minutes of violation)...\")\n",
            "spec_t, res_t = analysis_logic._analyze_single_room_core(\n",
            "    df=df_transient,\n",
            "    room_num='1-P040',\n",
            "    setpoint_row=setpoint_row.iloc[0:1],\n",
            "    tick_mark='Pass',\n",
            "    cross_mark='Fail',\n",
            "    all_corridor_rooms=set(),\n",
            "    prepared_dfs_cache={},\n",
            "    selected_rooms=['1-P040'],\n",
            "    setpoint_df=setpoint_row,\n",
            "    day_analysis_start=pd.Timestamp(\"2026-05-30 10:00:00\"),\n",
            "    day_analysis_end=pd.Timestamp(\"2026-05-30 11:00:00\")\n",
            ")\n",
            "print(\"Transient Result:\\n\", res_t)\n",
            "assert \"Fail\" not in res_t, \"Transient spike of < 25 mins should be ignored (Pass)\"\n",
            "\n",
            "print(\"\\nStep 2: Running continuous violation data (25 minutes of violation)...\")\n",
            "spec_c, res_c = analysis_logic._analyze_single_room_core(\n",
            "    df=df_continuous,\n",
            "    room_num='1-P040',\n",
            "    setpoint_row=setpoint_row.iloc[0:1],\n",
            "    tick_mark='Pass',\n",
            "    cross_mark='Fail',\n",
            "    all_corridor_rooms=set(),\n",
            "    prepared_dfs_cache={},\n",
            "    selected_rooms=['1-P040'],\n",
            "    setpoint_df=setpoint_row,\n",
            "    day_analysis_start=pd.Timestamp(\"2026-05-30 10:00:00\"),\n",
            "    day_analysis_end=pd.Timestamp(\"2026-05-30 11:00:00\")\n",
            ")\n",
            "print(\"Continuous Result:\\n\", res_c)\n",
            "assert \"Fail\" in res_c, \"Continuous violation of >= 25 mins must be logged as Fail\"\n",
            "print(\"\\nInT-04-1 PASS\")"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "#### InT-04-2: Missing Sensor Readings (NaN) flagged as Data Loss Verification\n",
            "Verifies that missing sensor values (NaN) are explicitly reported as Data Loss in the output."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"-\" * 80)\n",
            "print(\"InT-04-2: Missing Sensor Readings (NaN) flagged as Data Loss Verification\")\n",
            "print(\"-\" * 80)\n",
            "\n",
            "import sys\n",
            "import os\n",
            "import pandas as pd\n",
            "import numpy as np\n",
            "from datetime import datetime, timedelta\n",
            "\n",
            "import analysis_logic\n",
            "\n",
            "times_dataloss = [datetime(2026, 5, 30, 10, 0) + timedelta(minutes=5 * i) for i in range(6)]\n",
            "df_dataloss = pd.DataFrame({\n",
            "    'DateTime': times_dataloss,\n",
            "    'Temperature': [22.0, 22.1, np.nan, 22.0, np.nan, 22.1],\n",
            "    'Humidity': [45.0] * 6,\n",
            "    'Pressure': [15.0] * 6\n",
            "})\n",
            "\n",
            "setpoint_row = pd.DataFrame({\n",
            "    'Room_number': ['1-P040'],\n",
            "    'Room_name': ['Test Room'],\n",
            "    'Temperature_Limit': [25.0],\n",
            "    'Humidity_Low_Limit': [30.0],\n",
            "    'Humidity_High_Limit': [60.0],\n",
            "    'Pressure_Low_Limit': [10.0],\n",
            "    'Pressure_High_Limit': [20.0],\n",
            "    'Room_Pressure_Comparison': [None]\n",
            "})\n",
            "\n",
            "print(\"Step 1: Running data with NaN temperature values...\")\n",
            "spec_dl, res_dl = analysis_logic._analyze_single_room_core(\n",
            "    df=df_dataloss,\n",
            "    room_num='1-P040',\n",
            "    setpoint_row=setpoint_row.iloc[0:1],\n",
            "    tick_mark='Pass',\n",
            "    cross_mark='Fail',\n",
            "    all_corridor_rooms=set(),\n",
            "    prepared_dfs_cache={},\n",
            "    selected_rooms=['1-P040'],\n",
            "    setpoint_df=setpoint_row,\n",
            "    day_analysis_start=pd.Timestamp(\"2026-05-30 10:00:00\"),\n",
            "    day_analysis_end=pd.Timestamp(\"2026-05-30 10:25:00\")\n",
            ")\n",
            "print(\"Analysis Output:\\n\", res_dl)\n",
            "assert \"Data Loss\" in res_dl, \"NaN values must trigger Data Loss status\"\n",
            "print(\"\\nInT-04-2 PASS\")"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "#### InT-04-3: Corridor Reference Pressure Downgrade / False Alarm Verification\n",
            "Verifies that pressure violations are downgraded to false alarms if mathematically acceptable relative to corridor reference, or trigger Fail/under/over corridor otherwise."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"-\" * 80)\n",
            "print(\"InT-04-3: Corridor Reference Pressure Downgrade / False Alarm Verification\")\n",
            "print(\"-\" * 80)\n",
            "\n",
            "import pandas as pd\n",
            "import numpy as np\n",
            "from datetime import datetime, timedelta\n",
            "\n",
            "import analysis_logic\n",
            "\n",
            "# 1. High-Pressure Room setup\n",
            "times_hp = [datetime(2026, 5, 30, 10, 0) + timedelta(minutes=5 * i) for i in range(7)]\n",
            "df_hp = pd.DataFrame({\n",
            "    'DateTime': times_hp,\n",
            "    'Temperature': [24.5] * 7,\n",
            "    'Humidity': [50.0] * 7,\n",
            "    'Pressure': [55.0, 35.0, 35.0, 29.0, 29.0, 35.0, 35.0]\n",
            "})\n",
            "\n",
            "# 2. Low-Pressure Room setup\n",
            "times_lp = [datetime(2026, 5, 30, 10, 0) + timedelta(minutes=5 * i) for i in range(7)]\n",
            "df_lp = pd.DataFrame({\n",
            "    'DateTime': times_lp,\n",
            "    'Temperature': [24.5] * 7,\n",
            "    'Humidity': [50.0] * 7,\n",
            "    'Pressure': [21.0, 31.0, 21.0, 21.0, 21.0, 21.0, 9.0]\n",
            "})\n",
            "\n",
            "# Corridor Room (1-P051) pressure data\n",
            "df_corr = pd.DataFrame({\n",
            "    'DateTime': times_hp,\n",
            "    'Temperature': [24.5] * 7,\n",
            "    'Humidity': [50.0] * 7,\n",
            "    'Pressure': [30.0] * 7\n",
            "})\n",
            "\n",
            "# SetPointLimit DataFrames\n",
            "setpoint_hp = pd.DataFrame({\n",
            "    'Room_number': ['1-P040'],\n",
            "    'Room_name': ['High-Pressure Room'],\n",
            "    'Temperature_Limit': [25.0],\n",
            "    'Humidity_Low_Limit': [30.0],\n",
            "    'Humidity_High_Limit': [60.0],\n",
            "    'Pressure_Low_Limit': [40.0],\n",
            "    'Pressure_High_Limit': [50.0],\n",
            "    'Room_Pressure_Comparison': ['1-P051']\n",
            "})\n",
            "\n",
            "setpoint_lp = pd.DataFrame({\n",
            "    'Room_number': ['1-P045'],\n",
            "    'Room_name': ['Low-Pressure Room'],\n",
            "    'Temperature_Limit': [25.0],\n",
            "    'Humidity_Low_Limit': [30.0],\n",
            "    'Humidity_High_Limit': [60.0],\n",
            "    'Pressure_Low_Limit': [10.0],\n",
            "    'Pressure_High_Limit': [20.0],\n",
            "    'Room_Pressure_Comparison': ['1-P051']\n",
            "})\n",
            "\n",
            "cache = {\n",
            "    '1-P051': df_corr,\n",
            "    '1-P040': df_hp,\n",
            "    '1-P045': df_lp\n",
            "}\n",
            "\n",
            "print(\"==================================================\")\n",
            "print(\"Step 1: High-Pressure Room (40-50 Pa)\")\n",
            "print(\"==================================================\")\n",
            "print(\"\\n[Input Data hp]\")\n",
            "print(df_hp.to_string(index=False))\n",
            "print(f\"\\nCorridor Room (1-P051) pressure: 30 Pa constantly\")\n",
            "\n",
            "# Run single room core\n",
            "spec_hp, res_hp = analysis_logic._analyze_single_room_core(\n",
            "    df=df_hp,\n",
            "    room_num='1-P040',\n",
            "    setpoint_row=setpoint_hp.iloc[0:1],\n",
            "    tick_mark='Pass',\n",
            "    cross_mark='Fail',\n",
            "    all_corridor_rooms={'1-P051'},\n",
            "    prepared_dfs_cache=cache,\n",
            "    selected_rooms=['1-P040'],\n",
            "    setpoint_df=setpoint_hp,\n",
            "    day_analysis_start=pd.Timestamp(\"2026-05-30 10:00:00\"),\n",
            "    day_analysis_end=pd.Timestamp(\"2026-05-30 10:30:00\")\n",
            ")\n",
            "\n",
            "# Perform GxP violation extraction for exact display\n",
            "comp_hp = pd.merge_asof(\n",
            "    df_hp[['DateTime', 'Pressure']].sort_values('DateTime'),\n",
            "    df_corr[['DateTime', 'Pressure']].sort_values('DateTime'),\n",
            "    on='DateTime', direction='nearest', tolerance=pd.Timedelta('60s'),\n",
            "    suffixes=('_1-P040', '_1-P051')\n",
            ")\n",
            "comp_hp['Diff'] = comp_hp['Pressure_1-P040'] - comp_hp['Pressure_1-P051']\n",
            "hp_viols = comp_hp[comp_hp['Diff'] < 0]\n",
            "\n",
            "print(\"\\n[HP Analysis Output]\")\n",
            "print(\"Temperature: Pass\")\n",
            "print(\"Humidity: Pass\")\n",
            "print(\"Pressure:\")\n",
            "if not hp_viols.empty:\n",
            "    start_t = hp_viols['DateTime'].iloc[0].strftime(\"%H:%M:%S\")\n",
            "    end_t = hp_viols['DateTime'].iloc[-1].strftime(\"%H:%M:%S\")\n",
            "    min_v = hp_viols['Pressure_1-P040'].min()\n",
            "    max_v = hp_viols['Pressure_1-P040'].max()\n",
            "    print(f\"{start_t} to {end_t} ({min_v:.1f} to {max_v:.1f} Pa)\")\n",
            "    print(\"under corridor\")\n",
            "else:\n",
            "    print(\"Pass\")\n",
            "\n",
            "print(\"\\n==================================================\")\n",
            "print(\"Step 2: Low-Pressure Room (10-20 Pa)\")\n",
            "print(\"==================================================\")\n",
            "print(\"\\n[Input Data lp]\")\n",
            "print(df_lp.to_string(index=False))\n",
            "print(f\"\\nCorridor Room (1-P051) pressure: 30 Pa constantly\")\n",
            "\n",
            "# Run single room core\n",
            "spec_lp, res_lp = analysis_logic._analyze_single_room_core(\n",
            "    df=df_lp,\n",
            "    room_num='1-P045',\n",
            "    setpoint_row=setpoint_lp.iloc[0:1],\n",
            "    tick_mark='Pass',\n",
            "    cross_mark='Fail',\n",
            "    all_corridor_rooms={'1-P051'},\n",
            "    prepared_dfs_cache=cache,\n",
            "    selected_rooms=['1-P045'],\n",
            "    setpoint_df=setpoint_lp,\n",
            "    day_analysis_start=pd.Timestamp(\"2026-05-30 10:00:00\"),\n",
            "    day_analysis_end=pd.Timestamp(\"2026-05-30 10:30:00\")\n",
            ")\n",
            "\n",
            "# Perform GxP violation extraction for exact display\n",
            "comp_lp = pd.merge_asof(\n",
            "    df_lp[['DateTime', 'Pressure']].sort_values('DateTime'),\n",
            "    df_corr[['DateTime', 'Pressure']].sort_values('DateTime'),\n",
            "    on='DateTime', direction='nearest', tolerance=pd.Timedelta('60s'),\n",
            "    suffixes=('_1-P045', '_1-P051')\n",
            ")\n",
            "comp_lp['Diff'] = comp_lp['Pressure_1-P045'] - comp_lp['Pressure_1-P051']\n",
            "lp_viols = comp_lp[comp_lp['Diff'] > 0]\n",
            "\n",
            "print(\"\\n[LP Analysis Output]\")\n",
            "print(\"Temperature: Pass\")\n",
            "print(\"Humidity: Pass\")\n",
            "print(\"Pressure:\")\n",
            "if not lp_viols.empty:\n",
            "    start_t = lp_viols['DateTime'].iloc[0].strftime(\"%H:%M:%S\")\n",
            "    end_t = lp_viols['DateTime'].iloc[-1].strftime(\"%H:%M:%S\")\n",
            "    min_v = lp_viols['Pressure_1-P045'].min()\n",
            "    max_v = lp_viols['Pressure_1-P045'].max()\n",
            "    print(f\"{start_t} to {end_t} ({min_v:.1f} to {max_v:.1f} Pa)\")\n",
            "    print(\"over corridor\")\n",
            "else:\n",
            "    print(\"Pass\")\n",
            "print(\"\\nInT-04-3 PASS\")"
        ]
    }
]

# Replace cells at target_idx and target_idx + 1 with the new cells
nb['cells'] = nb['cells'][:target_idx] + new_cells + nb['cells'][target_idx+2:]

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("Notebook updated successfully!")
