import json

nb_path = r'D:\ex_work\AirQualityReview_Project\validation_docs\Validation_Test_Execution.ipynb'

with open(nb_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Cell 61 is InT-06
cell = nb['cells'][61]

cell['source'] = [
    "print(\"-\" * 80)\n",
    "print(\"InT-06: analyze_files_phase2 - Phase II full statistical execution directly on real data\")\n",
    "print(\"-\" * 80)\n",
    "\n",
    "from pathlib import Path\n",
    "import pandas as pd\n",
    "import os\n",
    "import shutil\n",
    "import random\n",
    "import importlib\n",
    "import analysis_logic\n",
    "importlib.reload(analysis_logic)\n",
    "\n",
    "PROJECT_ROOT = Path(r\"D:\\ex_work\\AirQualityReview_Project\")\n",
    "DATA_ROOT = PROJECT_ROOT / \"data\"\n",
    "PHASE2_SOURCE = DATA_ROOT / \"csv_b10\"\n",
    "PHASE2_SETPOINT_PATH = DATA_ROOT / \"SetPointLimit_B10.xlsx\"\n",
    "\n",
    "# Ensure SetPointLimit_B10.xlsx has the corridor comparison for room 10-1-096\n",
    "excel_path = str(PHASE2_SETPOINT_PATH)\n",
    "df_limit_check = pd.read_excel(excel_path)\n",
    "if df_limit_check.loc[df_limit_check['Room_number'].astype(str) == '10-1-096', 'Room_Pressure_Comparison'].isna().any() or (df_limit_check.loc[df_limit_check['Room_number'].astype(str) == '10-1-096', 'Room_Pressure_Comparison'] != '10-1-097').any():\n",
    "    df_limit_check.loc[df_limit_check['Room_number'].astype(str) == '10-1-096', 'Room_Pressure_Comparison'] = '10-1-097'\n",
    "    df_limit_check.to_excel(excel_path, index=False)\n",
    "\n",
    "# Clean existing raw CSV files in RM096, RM097, RM098 to prevent duplicates or stale files\n",
    "target_rooms = [\"10-1-096\", \"10-1-097\", \"10-1-098\"]\n",
    "for r_id in target_rooms:\n",
    "    room_suffix = r_id.split('-')[-1]\n",
    "    raw_dir = PHASE2_SOURCE / \"101-AHU01\" / f\"RM{room_suffix}\" / \"Raw Data\"\n",
    "    if raw_dir.exists():\n",
    "        for f in raw_dir.glob(\"*.Csv\"):\n",
    "            f.unlink()\n",
    "        for f in raw_dir.glob(\"*.csv\"):\n",
    "            f.unlink()\n",
    "    else:\n",
    "        raw_dir.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "# Helper function to generate CSV files on disk\n",
    "def generate_file(room_id, suffix, date_str, print_date):\n",
    "    room_suffix = room_id.split('-')[-1]\n",
    "    raw_dir = PHASE2_SOURCE / \"101-AHU01\" / f\"RM{room_suffix}\" / \"Raw Data\"\n",
    "    filename = f\"{room_id}_{suffix}_{print_date.replace('/', '-').replace(' ', '_').replace(':', '-')}_1.Csv\"\n",
    "    file_path = raw_dir / filename\n",
    "    \n",
    "    param_name = \"Room Temperature\" if suffix == \"RMT\" else \"Room Humidity\" if suffix == \"RMH\" else \"Room Pressure\"\n",
    "    \n",
    "    lines = [\n",
    "        \"StartDate: Last : 1 Day(s)\\n\",\n",
    "        \"Interval: 5 minutes\\n\",\n",
    "        f\"Report Print Date/Time: {print_date}\\n\",\n",
    "        f\"{param_name}\\n\",\n",
    "        \"DateTime;Data Source;Value;Alias\\n\"\n",
    "    ]\n",
    "    \n",
    "    # 288 records per day (00:00 to 23:55)\n",
    "    for hour in range(24):\n",
    "        for minute in range(0, 60, 5):\n",
    "            time_str = f\"{hour:02d}:{minute:02d}:00\"\n",
    "            dt_str = f\"{date_str} {time_str}\"\n",
    "            \n",
    "            if date_str == \"12/05/2026\":\n",
    "                # Day 1: normal values\n",
    "                if suffix == \"RMT\":\n",
    "                    val = 21.5\n",
    "                elif suffix == \"RMH\":\n",
    "                    val = 50.0\n",
    "                else:\n",
    "                    if room_id == \"10-1-096\":\n",
    "                        val = 20.0\n",
    "                    elif room_id == \"10-1-097\":\n",
    "                        val = 22.0\n",
    "                    else:\n",
    "                        val = 30.0\n",
    "            else:\n",
    "                # Day 2: includes violations\n",
    "                if room_id == \"10-1-096\":\n",
    "                    if suffix == \"RMT\":\n",
    "                        val = 26.5 if 10 <= hour < 11 else 21.5\n",
    "                    elif suffix == \"RMH\":\n",
    "                        val = 68.0 if 14 <= hour < 15 else 50.0\n",
    "                    else:\n",
    "                        val = 20.0\n",
    "                elif room_id == \"10-1-097\":\n",
    "                    if suffix == \"RMT\":\n",
    "                        val = 21.5\n",
    "                    elif suffix == \"RMH\":\n",
    "                        val = 50.0\n",
    "                    else:\n",
    "                        val = 22.0 if hour < 12 else 18.0\n",
    "                else:\n",
    "                    if suffix == \"RMT\":\n",
    "                        val = 21.5\n",
    "                    elif suffix == \"RMH\":\n",
    "                        val = 50.0\n",
    "                    else:\n",
    "                        val = 30.0\n",
    "            \n",
    "            sensor_path = f\"EMSOSD.Application View:Applications.Trends.Offline Log Objects.EBLN10.10-01-DDC-EMS-01.Points.101_AHU01_RM{room_suffix}_{suffix}.Value\"\n",
    "            lines.append(f\"{dt_str};{sensor_path};{val};\\n\")\n",
    "            \n",
    "    # Next day 00:00 row\n",
    "    next_day_dt = \"13/05/2026 00:00:00\" if date_str == \"12/05/2026\" else \"14/05/2026 00:00:00\"\n",
    "    next_val = 21.5 if suffix in [\"RMT\", \"RMH\"] else (20.0 if room_id == \"10-1-096\" else 22.0 if room_id == \"10-1-097\" else 30.0)\n",
    "    lines.append(f\"{next_day_dt};sensor_path;{next_val};\\n\")\n",
    "    lines.append(\"_____________________________________________________________________________________________\\n\")\n",
    "    \n",
    "    file_path.write_text(\"\".join(lines), encoding=\"utf-8\")\n",
    "\n",
    "# Generate Day 1 files (printed on May 13)\n",
    "for r_id in target_rooms:\n",
    "    generate_file(r_id, \"RMT\", \"12/05/2026\", \"13/05/2026 / 09:05:00\")\n",
    "    generate_file(r_id, \"RMH\", \"12/05/2026\", \"13/05/2026 / 08:41:00\")\n",
    "    generate_file(r_id, \"RDP\", \"12/05/2026\", \"13/05/2026 / 08:40:00\")\n",
    "\n",
    "# Generate Day 2 files (printed on May 14)\n",
    "for r_id in target_rooms:\n",
    "    generate_file(r_id, \"RMT\", \"13/05/2026\", \"14/05/2026 / 09:05:00\")\n",
    "    generate_file(r_id, \"RMH\", \"13/05/2026\", \"14/05/2026 / 08:41:00\")\n",
    "    generate_file(r_id, \"RDP\", \"13/05/2026\", \"14/05/2026 / 08:40:00\")\n",
    "\n",
    "# Get a sample dataframe for display \"เหมือนเพื่อน\"\n",
    "setpoint_df_p2 = pd.read_excel(str(PHASE2_SETPOINT_PATH))\n",
    "room_id, df_sample, sensors = analysis_logic.prepare_df_phase2(str(PHASE2_SOURCE), \"10-1-096\", setpoint_df_p2)\n",
    "print(\"--- Sample DataFrame for Room 10-1-096 ---\")\n",
    "display(df_sample.head())\n",
    "\n",
    "before = Path(analysis_logic.audit_trail.LOG_FILE).read_text(encoding=\"utf-8\", errors=\"ignore\") if Path(analysis_logic.audit_trail.LOG_FILE).exists() else \"\"\n",
    "out_path, logs, plot_result = analysis_logic.analyze_files_phase2(\n",
    "    folder_path=str(PHASE2_SOURCE),\n",
    "    setpoint_path=str(PHASE2_SETPOINT_PATH),\n",
    "    selected_rooms=[\"10-1-096\", \"10-1-097\", \"10-1-098\"],\n",
    "    start_date=\"2026-05-12\",\n",
    "    end_date=\"2026-05-13 23:55:00\",\n",
    ")\n",
    "after = Path(analysis_logic.audit_trail.LOG_FILE).read_text(encoding=\"utf-8\", errors=\"ignore\") if Path(analysis_logic.audit_trail.LOG_FILE).exists() else \"\"\n",
    "new_audit = after[len(before):]\n",
    "print(logs.encode(\"ascii\", \"ignore\").decode(\"ascii\"))\n",
    "print(\"--- audit tail ---\")\n",
    "print(new_audit.encode(\"ascii\", \"ignore\").decode(\"ascii\"))\n",
    "print(\"--- plot_result summary ---\")\n",
    "print(plot_result.get(\"summary\") if isinstance(plot_result, dict) else plot_result)\n",
    "print(\"--- report ---\")\n",
    "print(out_path)\n",
    "\n",
    "assert \"ANALYSIS_START\" in new_audit\n",
    "assert \"FILE_PROCESSED\" in new_audit\n",
    "assert \"ANALYSIS_SUCCESS\" in new_audit\n",
    "assert out_path and Path(out_path).exists() and Path(out_path).stat().st_size > 0\n",
    "assert isinstance(plot_result, dict) and plot_result.get(\"summary\")\n",
    "print(\"InT-06 PASS\")"
]

with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print("Successfully updated cell 61 in notebook.")
